"""Initial schema with UUID and slug

Revision ID: edc4aba54fe6
Revises: 
Create Date: 2025-11-14 07:04:32.201967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc4aba54fe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['asset_db.asset_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='asset_db'
    )
    op.create_index(op.f('ix_asset_db_asset_categories_code'), 'asset_categories', ['code'], unique=True, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_categories_id'), 'asset_categories', ['id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_categories_slug'), 'asset_categories', ['slug'], unique=True, schema='asset_db')
    op.create_table('assets',
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('FIXED_ASSET', 'TOOL', name='assettype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=True),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('depreciation_method', sa.Enum('STRAIGHT_LINE', 'DECLINING_BALANCE', name='depreciationmethod'), nullable=True),
    sa.Column('useful_life_months', sa.Integer(), nullable=True),
    sa.Column('residual_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('warranty_start_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('warranty_provider', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_USE', 'AVAILABLE', 'MAINTENANCE', 'BROKEN', 'DISPOSED', name='assetstatus'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('current_user_id', sa.String(length=36), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['asset_db.asset_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='asset_db'
    )
    op.create_index(op.f('ix_asset_db_assets_asset_code'), 'assets', ['asset_code'], unique=True, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_asset_type'), 'assets', ['asset_type'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_category_id'), 'assets', ['category_id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_current_user_id'), 'assets', ['current_user_id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_department_id'), 'assets', ['department_id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_id'), 'assets', ['id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_purchase_date'), 'assets', ['purchase_date'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_slug'), 'assets', ['slug'], unique=True, schema='asset_db')
    op.create_index(op.f('ix_asset_db_assets_status'), 'assets', ['status'], unique=False, schema='asset_db')
    op.create_table('asset_assignments',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('handover_document_url', sa.String(length=500), nullable=True),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('returned_by', sa.String(length=36), nullable=True),
    sa.Column('return_condition', sa.Enum('GOOD', 'DAMAGED', 'BROKEN', name='returncondition'), nullable=True),
    sa.Column('return_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', name='assignmentstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_db.assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='asset_db'
    )
    op.create_index(op.f('ix_asset_db_asset_assignments_asset_id'), 'asset_assignments', ['asset_id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_assignments_assigned_date'), 'asset_assignments', ['assigned_date'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_assignments_id'), 'asset_assignments', ['id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_assignments_slug'), 'asset_assignments', ['slug'], unique=True, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_assignments_status'), 'asset_assignments', ['status'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_assignments_user_id'), 'asset_assignments', ['user_id'], unique=False, schema='asset_db')
    op.create_table('asset_attachments',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('INVOICE', 'WARRANTY', 'PHOTO', 'DOCUMENT', name='filetype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_db.assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='asset_db'
    )
    op.create_index(op.f('ix_asset_db_asset_attachments_asset_id'), 'asset_attachments', ['asset_id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_attachments_file_type'), 'asset_attachments', ['file_type'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_attachments_id'), 'asset_attachments', ['id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_attachments_slug'), 'asset_attachments', ['slug'], unique=True, schema='asset_db')
    op.create_table('asset_depreciation_records',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('opening_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('depreciation_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('calculated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_db.assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_month', name='uk_asset_period'),
    schema='asset_db'
    )
    op.create_index(op.f('ix_asset_db_asset_depreciation_records_asset_id'), 'asset_depreciation_records', ['asset_id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_depreciation_records_id'), 'asset_depreciation_records', ['id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_depreciation_records_period_month'), 'asset_depreciation_records', ['period_month'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_asset_depreciation_records_slug'), 'asset_depreciation_records', ['slug'], unique=True, schema='asset_db')
    op.create_table('maintenance_records',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('technician', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_db.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='asset_db'
    )
    op.create_index(op.f('ix_asset_db_maintenance_records_asset_id'), 'maintenance_records', ['asset_id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_maintenance_records_id'), 'maintenance_records', ['id'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_maintenance_records_maintenance_date'), 'maintenance_records', ['maintenance_date'], unique=False, schema='asset_db')
    op.create_index(op.f('ix_asset_db_maintenance_records_slug'), 'maintenance_records', ['slug'], unique=True, schema='asset_db')
    op.create_index(op.f('ix_asset_db_maintenance_records_status'), 'maintenance_records', ['status'], unique=False, schema='asset_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_db_maintenance_records_status'), table_name='maintenance_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_maintenance_records_slug'), table_name='maintenance_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_maintenance_records_maintenance_date'), table_name='maintenance_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_maintenance_records_id'), table_name='maintenance_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_maintenance_records_asset_id'), table_name='maintenance_records', schema='asset_db')
    op.drop_table('maintenance_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_depreciation_records_slug'), table_name='asset_depreciation_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_depreciation_records_period_month'), table_name='asset_depreciation_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_depreciation_records_id'), table_name='asset_depreciation_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_depreciation_records_asset_id'), table_name='asset_depreciation_records', schema='asset_db')
    op.drop_table('asset_depreciation_records', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_attachments_slug'), table_name='asset_attachments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_attachments_id'), table_name='asset_attachments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_attachments_file_type'), table_name='asset_attachments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_attachments_asset_id'), table_name='asset_attachments', schema='asset_db')
    op.drop_table('asset_attachments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_assignments_user_id'), table_name='asset_assignments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_assignments_status'), table_name='asset_assignments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_assignments_slug'), table_name='asset_assignments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_assignments_id'), table_name='asset_assignments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_assignments_assigned_date'), table_name='asset_assignments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_assignments_asset_id'), table_name='asset_assignments', schema='asset_db')
    op.drop_table('asset_assignments', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_status'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_slug'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_purchase_date'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_id'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_department_id'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_current_user_id'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_category_id'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_asset_type'), table_name='assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_assets_asset_code'), table_name='assets', schema='asset_db')
    op.drop_table('assets', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_categories_slug'), table_name='asset_categories', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_categories_id'), table_name='asset_categories', schema='asset_db')
    op.drop_index(op.f('ix_asset_db_asset_categories_code'), table_name='asset_categories', schema='asset_db')
    op.drop_table('asset_categories', schema='asset_db')
    # ### end Alembic commands ###
