"""Initial schema with UUID and slug

Revision ID: c17fe98c9985
Revises: 
Create Date: 2025-11-15 01:44:06.076638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17fe98c9985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_permissions_id'), 'permissions', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_permissions_name'), 'permissions', ['name'], unique=True, schema='auth_db')
    op.create_index(op.f('ix_auth_db_permissions_slug'), 'permissions', ['slug'], unique=True, schema='auth_db')
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_roles_id'), 'roles', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_roles_name'), 'roles', ['name'], unique=True, schema='auth_db')
    op.create_index(op.f('ix_auth_db_roles_slug'), 'roles', ['slug'], unique=True, schema='auth_db')
    op.create_table('role_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('original_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_db.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_role_history_id'), 'role_history', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_role_history_role_id'), 'role_history', ['role_id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_role_history_slug'), 'role_history', ['slug'], unique=True, schema='auth_db')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_db.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_db.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='auth_db'
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('ad_sync_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('require_password_change', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_db.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_sync_id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_users_email'), 'users', ['email'], unique=True, schema='auth_db')
    op.create_index(op.f('ix_auth_db_users_id'), 'users', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_users_slug'), 'users', ['slug'], unique=True, schema='auth_db')
    op.create_index(op.f('ix_auth_db_users_username'), 'users', ['username'], unique=True, schema='auth_db')
    op.create_table('mfa_backup_codes',
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_db.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_mfa_backup_codes_id'), 'mfa_backup_codes', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_mfa_backup_codes_slug'), 'mfa_backup_codes', ['slug'], unique=True, schema='auth_db')
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_db.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_password_reset_tokens_slug'), 'password_reset_tokens', ['slug'], unique=True, schema='auth_db')
    op.create_index(op.f('ix_auth_db_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True, schema='auth_db')
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_db.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_refresh_tokens_slug'), 'refresh_tokens', ['slug'], unique=True, schema='auth_db')
    op.create_index(op.f('ix_auth_db_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True, schema='auth_db')
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('ad_sync_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('require_password_change', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('original_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_db.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_db'
    )
    op.create_index(op.f('ix_auth_db_user_history_id'), 'user_history', ['id'], unique=False, schema='auth_db')
    op.create_index(op.f('ix_auth_db_user_history_slug'), 'user_history', ['slug'], unique=True, schema='auth_db')
    op.create_index(op.f('ix_auth_db_user_history_user_id'), 'user_history', ['user_id'], unique=False, schema='auth_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_db_user_history_user_id'), table_name='user_history', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_user_history_slug'), table_name='user_history', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_user_history_id'), table_name='user_history', schema='auth_db')
    op.drop_table('user_history', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_refresh_tokens_token'), table_name='refresh_tokens', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_refresh_tokens_slug'), table_name='refresh_tokens', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_refresh_tokens_id'), table_name='refresh_tokens', schema='auth_db')
    op.drop_table('refresh_tokens', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_password_reset_tokens_token'), table_name='password_reset_tokens', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_password_reset_tokens_slug'), table_name='password_reset_tokens', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_password_reset_tokens_id'), table_name='password_reset_tokens', schema='auth_db')
    op.drop_table('password_reset_tokens', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_mfa_backup_codes_slug'), table_name='mfa_backup_codes', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_mfa_backup_codes_id'), table_name='mfa_backup_codes', schema='auth_db')
    op.drop_table('mfa_backup_codes', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_users_username'), table_name='users', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_users_slug'), table_name='users', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_users_id'), table_name='users', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_users_email'), table_name='users', schema='auth_db')
    op.drop_table('users', schema='auth_db')
    op.drop_table('role_permissions', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_role_history_slug'), table_name='role_history', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_role_history_role_id'), table_name='role_history', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_role_history_id'), table_name='role_history', schema='auth_db')
    op.drop_table('role_history', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_roles_slug'), table_name='roles', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_roles_name'), table_name='roles', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_roles_id'), table_name='roles', schema='auth_db')
    op.drop_table('roles', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_permissions_slug'), table_name='permissions', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_permissions_name'), table_name='permissions', schema='auth_db')
    op.drop_index(op.f('ix_auth_db_permissions_id'), table_name='permissions', schema='auth_db')
    op.drop_table('permissions', schema='auth_db')
    # ### end Alembic commands ###
