"""Initial schema with UUID and slug

Revision ID: 14ed566dbd5d
Revises: 
Create Date: 2025-11-14 07:04:35.210502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ed566dbd5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_db'
    )
    op.create_index(op.f('ix_admin_db_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_audit_logs_module_name'), 'audit_logs', ['module_name'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_audit_logs_slug'), 'audit_logs', ['slug'], unique=True, schema='admin_db')
    op.create_index(op.f('ix_admin_db_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='admin_db')
    op.create_table('module_settings',
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.Enum('STRING', 'INTEGER', 'BOOLEAN', 'JSON', name='settingtype'), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('validation_rules', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_db'
    )
    op.create_index(op.f('ix_admin_db_module_settings_id'), 'module_settings', ['id'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_module_settings_module_name'), 'module_settings', ['module_name'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_module_settings_setting_key'), 'module_settings', ['setting_key'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_module_settings_slug'), 'module_settings', ['slug'], unique=True, schema='admin_db')
    op.create_table('system_logs',
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_db'
    )
    op.create_index(op.f('ix_admin_db_system_logs_id'), 'system_logs', ['id'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_system_logs_log_level'), 'system_logs', ['log_level'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_system_logs_module_name'), 'system_logs', ['module_name'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_system_logs_slug'), 'system_logs', ['slug'], unique=True, schema='admin_db')
    op.create_table('system_modules',
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='modulestatus'), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('frontend_endpoint', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('allowed_roles', sa.Text(), nullable=True),
    sa.Column('is_system_module', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_db'
    )
    op.create_index(op.f('ix_admin_db_system_modules_id'), 'system_modules', ['id'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_system_modules_module_name'), 'system_modules', ['module_name'], unique=True, schema='admin_db')
    op.create_index(op.f('ix_admin_db_system_modules_slug'), 'system_modules', ['slug'], unique=True, schema='admin_db')
    op.create_table('trash_config',
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('auto_delete_days', sa.Integer(), nullable=False),
    sa.Column('enable_soft_delete', sa.Boolean(), nullable=False),
    sa.Column('enable_restore', sa.Boolean(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('cascade_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_db'
    )
    op.create_index(op.f('ix_admin_db_trash_config_id'), 'trash_config', ['id'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_config_module_name'), 'trash_config', ['module_name'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_config_resource_type'), 'trash_config', ['resource_type'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_config_slug'), 'trash_config', ['slug'], unique=True, schema='admin_db')
    op.create_table('trash_items',
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_name', sa.String(length=500), nullable=False),
    sa.Column('resource_data', sa.JSON(), nullable=False),
    sa.Column('deleted_by', sa.String(length=36), nullable=False),
    sa.Column('deleted_by_email', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.Column('is_restorable', sa.Boolean(), nullable=False),
    sa.Column('permanent_delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restore_dependencies', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.String(length=36), nullable=True),
    sa.Column('restored_by_email', sa.String(length=255), nullable=True),
    sa.Column('permanently_deleted_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admin_db'
    )
    op.create_index(op.f('ix_admin_db_trash_items_deleted_at'), 'trash_items', ['deleted_at'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_items_deleted_by'), 'trash_items', ['deleted_by'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_items_id'), 'trash_items', ['id'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_items_module_name'), 'trash_items', ['module_name'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_items_permanent_delete_at'), 'trash_items', ['permanent_delete_at'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_items_resource_id'), 'trash_items', ['resource_id'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_items_resource_type'), 'trash_items', ['resource_type'], unique=False, schema='admin_db')
    op.create_index(op.f('ix_admin_db_trash_items_slug'), 'trash_items', ['slug'], unique=True, schema='admin_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_db_trash_items_slug'), table_name='trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_items_resource_type'), table_name='trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_items_resource_id'), table_name='trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_items_permanent_delete_at'), table_name='trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_items_module_name'), table_name='trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_items_id'), table_name='trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_items_deleted_by'), table_name='trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_items_deleted_at'), table_name='trash_items', schema='admin_db')
    op.drop_table('trash_items', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_config_slug'), table_name='trash_config', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_config_resource_type'), table_name='trash_config', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_config_module_name'), table_name='trash_config', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_trash_config_id'), table_name='trash_config', schema='admin_db')
    op.drop_table('trash_config', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_system_modules_slug'), table_name='system_modules', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_system_modules_module_name'), table_name='system_modules', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_system_modules_id'), table_name='system_modules', schema='admin_db')
    op.drop_table('system_modules', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_system_logs_slug'), table_name='system_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_system_logs_module_name'), table_name='system_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_system_logs_log_level'), table_name='system_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_system_logs_id'), table_name='system_logs', schema='admin_db')
    op.drop_table('system_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_module_settings_slug'), table_name='module_settings', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_module_settings_setting_key'), table_name='module_settings', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_module_settings_module_name'), table_name='module_settings', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_module_settings_id'), table_name='module_settings', schema='admin_db')
    op.drop_table('module_settings', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_audit_logs_user_id'), table_name='audit_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_audit_logs_slug'), table_name='audit_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_audit_logs_resource_type'), table_name='audit_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_audit_logs_module_name'), table_name='audit_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_audit_logs_id'), table_name='audit_logs', schema='admin_db')
    op.drop_index(op.f('ix_admin_db_audit_logs_action'), table_name='audit_logs', schema='admin_db')
    op.drop_table('audit_logs', schema='admin_db')
    # ### end Alembic commands ###
